replicaCount: 3

image:
  repository: 081073840758.dkr.ecr.us-east-1.amazonaws.com/sre-learning/payment-service
  tag: latest
  pullPolicy: Always

config:
  APP_PORT: "8080"
  LOG_LEVEL: "warn"
  KAFKA_BROKER: "kafka.uat.svc:9092"